#!/bin/bash -x

#PBS -l select=1:ncpus=256:mpiprocs=113:model=tur_ath
#PBS -l walltime=24:00:00
#PBS -l place=scatter:excl
#PBS -q long
#PBS -j oe

# Switch to ProEnv-intel instead of PrgEnv-cray
source /opt/cray/pe/modules/3.2.11.7/init/bash
module swap PrgEnv-cray PrgEnv-intel

mpiexec -np 113 ./mitgcmuv
